name = "sysmansquadblog_theme"
license = "GNU"
licenselink = "https://github.com/SysManSquad/sysmansquadblog/blob/master/LICENSE"
description = "Hugo Theme for www.sysmansquad.com"
homepage = "https://github.com/SysManSquad/sysmansquadblog/"
tags = ["blog"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "AdamGrossTX"
  homepage = "https://github.com/AdamGrossTX"